---

driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: false
  instance_type: t2.micro
  associate_public_ip: true

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 2

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: amazon
    driver:
      image_search:
        owner-alias: "amazon"
        name: amzn-ami*2016.03*gp2
    transport:
      username: ec2-user
    provisioner:
      ansible_platform: "amazon" # Autodetect is failing for some reason :(

suites:
  - name: default
  - name: modules
    provisioner:
      recursive_additional_copy_path: test/integration/modules/files
