# <% load "#{File.dirname(__FILE__)}/test/kitchen_docker.rb" %>

---

driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

transport:
  # Looks like this is still a issue: https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 1

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 2
  role_name: nginx

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
    driver_config:
      dockerfile: test/Dockerfile.centos7
      run_command: /usr/sbin/init # Start systemd as root process
    attributes:
      systemd: true

suites:
  - name: default
  - name: modules
    provisioner:
      recursive_additional_copy_path: test/integration/modules/files
